class ChangeObjective3 < ActiveRecord::Migration
  def change
    remove_column :objectives, :no0, :boolean
    remove_column :objectives, :no1, :boolean
    remove_column :objectives, :no2, :boolean
    remove_column :objectives, :no3, :boolean
    remove_column :objectives, :no4, :boolean
    remove_column :objectives, :no5, :boolean
    remove_column :objectives, :no6, :boolean
    remove_column :objectives, :no7, :boolean
    remove_column :objectives, :no8, :boolean
    remove_column :objectives, :no9, :boolean
    remove_column :objectives, :no10, :boolean
    remove_column :objectives, :no11, :boolean
    remove_column :objectives, :no12, :boolean
    remove_column :objectives, :no13, :boolean
    remove_column :objectives, :no14, :boolean
    remove_column :objectives, :no15, :boolean
    remove_column :objectives, :no16, :boolean
    remove_column :objectives, :no17, :boolean
    remove_column :objectives, :no18, :boolean
    remove_column :objectives, :no19, :boolean
    remove_column :objectives, :no20, :boolean
    remove_column :objectives, :no21, :boolean
    remove_column :objectives, :no22, :boolean
    remove_column :objectives, :no23, :boolean
    remove_column :objectives, :no24, :boolean
    remove_column :objectives, :no25, :boolean
    remove_column :objectives, :no26, :boolean
    remove_column :objectives, :no27, :boolean
    remove_column :objectives, :no28, :boolean
    remove_column :objectives, :no29, :boolean
    remove_column :objectives, :no30, :boolean
    remove_column :objectives, :no31, :boolean
    remove_column :objectives, :no32, :boolean
    remove_column :objectives, :no33, :boolean
    remove_column :objectives, :no34, :boolean
    remove_column :objectives, :no35, :boolean
    remove_column :objectives, :no36, :boolean
    remove_column :objectives, :no37, :boolean
    remove_column :objectives, :no38, :boolean
    remove_column :objectives, :no39, :boolean
  end
end
