class ChangeObjective4 < ActiveRecord::Migration
  def change
    add_column :objectives, :no0, :integer
    add_column :objectives, :no1, :integer
    add_column :objectives, :no2, :integer
    add_column :objectives, :no3, :integer
    add_column :objectives, :no4, :integer
    add_column :objectives, :no5, :integer
    add_column :objectives, :no6, :integer
    add_column :objectives, :no7, :integer
    add_column :objectives, :no8, :integer
    add_column :objectives, :no9, :integer
    add_column :objectives, :no10, :integer
    add_column :objectives, :no11, :integer
    add_column :objectives, :no12, :integer
    add_column :objectives, :no13, :integer
    add_column :objectives, :no14, :integer
    add_column :objectives, :no15, :integer
    add_column :objectives, :no16, :integer
    add_column :objectives, :no17, :integer
    add_column :objectives, :no18, :integer
    add_column :objectives, :no19, :integer
    add_column :objectives, :no20, :integer
    add_column :objectives, :no21, :integer
    add_column :objectives, :no22, :integer
    add_column :objectives, :no23, :integer
    add_column :objectives, :no24, :integer
    add_column :objectives, :no25, :integer
    add_column :objectives, :no26, :integer
    add_column :objectives, :no27, :integer
    add_column :objectives, :no28, :integer
    add_column :objectives, :no29, :integer
    add_column :objectives, :no30, :integer
    add_column :objectives, :no31, :integer
    add_column :objectives, :no32, :integer
    add_column :objectives, :no33, :integer
    add_column :objectives, :no34, :integer
    add_column :objectives, :no35, :integer
    add_column :objectives, :no36, :integer
    add_column :objectives, :no37, :integer
    add_column :objectives, :no38, :integer
    add_column :objectives, :no39, :integer
  end
end
